version: '3'
services:
  db:
    image: postgres:13.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
    command: bash -c "bin/rails db:migrate && bin/rails test"



  test:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: bundle exec rspec
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
    

volumes:
  postgres-data:
